[Refactor] JPA 마이그레이션 리뷰
prgrms-be-devcourse/NBE1_2_Team10 pull request #134
Opened 2024-10-17 03:20 UTC by hgh1472

## 📌 과제 설명 

movie 도메인 JPA로 마이그레이션을 진행했습니다. 한줄평에서 유저랑 관련되어 있는 부분이 있어서 대충 user 부분까지 작업하긴 했습니다! 이전 PR이 있어서 Merge되면 **추 후에 다시 브랜치파서 작업할 계획입니다.** 이 PR은 `코드 리뷰용`으로 올렸습니다!

## 👩‍💻 요구 사항과 구현 내용 

주 내용은 다음과 같습니다!

- `CachedMovieEntity` JPA Entity로 등록 2a2726de1e6675fb51cbca6d3a761c0c9d3cda58
- 기존 영화 Repository를 JPA Repository를 사용하도록 변경
  - 96afe050fd798f0ad706ccb5511b1623fb3dd26f
  - a29ebf236afd23c58e0c9b64f6c67441b40d536d
  - 3ed46bf683dd36e1812968c990a404c1635c0da3
- JPA 변경에 따른 서비스 로직 수정 및 페이징 처리 변경
  - 60eaf6e782d01df0acd4664937686ce1afa3f827
  - 41be7d11e236017ac7a8df817d0f549773f8988b
  - c4e4dc94ff00ed329d25e9008284d2499717854d
- `CommentEntity` JPA Entity로 등록 aa065e05dd856eb53ef61f31aaa6871fd4ccc6df
- `한줄평 좋아요, 싫어요 Entity 추가 0a7f304126d0b1240260b9fd3ef6aba9fabff3e3
- 한줄평 리포지토리 JPA로 변경 및 페이징 처리 수정
  - 2c9ca12cfdfcd08a6ad532da56f99222c8c20362
  - 59be79f01efe1a1dfd149ea37daf9ca4502e68cc
  - b1a99abfab5d9a9317fa0a3b7a23c5890b9afa35
- 한줄평 좋아요/싫어요 JPA로 변경
  - 158333ff6bc6a06a2210090e374447ed2f7f6a2a
- JPA 변경에 따른 한줄평 서비스 코드 수정 9cfebeafe62147de84969439608c852042609898

## ✅ PR 포인트 & 궁금한 점 
페이징 처리를 스프링에서 제공하는 `Page<>` 를 사용하였습니다.
기존에 `List<>`로만 제공하는 것보다 장점이, 조회 시 전체 개수또한 알려줘서 프론트에서 전체 개수에 따른 전체 페이지를 보여주는데 더 좋을 것 같기도하고 페이징 처리한 것에 대해 더 확실한 것 같아요!

2024-10-17 07:08 UTC, jbw9964 requested changes

2024-10-17 07:08 UTC, jbw9964 commented on application/src/main/java/core/application/users/service/UserServiceImpl.java
> +        if (userRepository.existsByUserId(userId)) {
유저가 삭제되었는데 `DB 에 유저가 존재하는지 확인` 하는 건가요?

거기에 `존재하면` 성공 메시지를 보내는 건가요?? 뭐징?

2024-10-17 07:10 UTC, jbw9964 requested changes
직접 `checkout` 해서 실행해보니 몇몇 `compile error` 가 있네요.

수정 후 머지 하셔야 될 것 같습니다.

2024-10-17 07:11 UTC, jbw9964 requested changes
잘못 적었어요

2024-10-17 07:50 UTC, TrixieL20 commented on application/src/main/java/core/application/users/service/UserServiceImpl.java
> +        if (userRepository.existsByUserId(userId)) {
userRepository.deleteUser(userId)의 return 값은 삭제한 행의 수이므로 1일 때 한 명만 제대로 삭제되었다고 나타내는 것 입니다.

2024-10-17 07:52 UTC, hgh1472 commented on application/src/main/java/core/application/users/models/entities/UserEntity.java
>      private UUID     userId;
GeneratedValue로 `UUID`로 가능한가요??
UUID라 안된다는 의견이 아니라, 저는 auto_increment같은 경우만 되는 줄로만 알고있어서 `@PrePersist`를 통해서 영속상태에 들어가기 전에 userId를 지정해줬습니다!

2024-10-17 07:54 UTC, hgh1472 commented on application/src/main/java/core/application/movies/repositories/comment/JpaCommentRepository.java
> +			"CASE WHEN l.commentLikeId IS NOT NULL THEN true ELSE false END, " +
제가 구현했을 때 사용자별로 한줄평 좋아요 여부를 보여주려고 구현했어요.
그런데 Entity 자체에 그 내용을 담을 순 없어서 `Repository`에서 바로 DTO로 반환될 수 있게 구현했던걸 유지했습니다.
`@Query`에 있는 `CommentRespDTO`를 반환하고, 이에 맞게 값을 넣어주는 내용이에요!

2024-10-17 07:55 UTC, hgh1472 commented on application/src/main/java/core/application/movies/repositories/comment/JpaCommentRepository.java
> +			"LEFT JOIN CommentLike l ON c.commentId = l.comment.commentId AND l.userId = :userId " +
`User`쪽을 어느정도 냅두고 하다보니 저기서 멈춰진 것 같아요!
한줄평도 유저랑 연관되어 있어서 하다보니 `User`도 하게 되서 일단 지금 다시 push 해놓겠습니다!

2024-10-17 07:56 UTC, hgh1472 commented on application/src/main/java/core/application/movies/repositories/movie/JpaMovieRepository.java
> +	@Query("select m from CachedMovieEntity m order by m.sumOfRating / m.commentCount desc limit :num")
0인 상황도 고려해야될 것 같아요..!
아마 저 연산은 정수를 기준으로 정렬하지 않을까 싶습니다 정확한 내용은 저도 확인해볼게요!

2024-10-17 07:56 UTC, hgh1472 commented on application/src/main/java/core/application/movies/models/entities/CommentEntity.java
> +	@PrePersist
수정될 때는 아닌 것으로 알고있어요! DB에 저장될 때를 기준으로 알고 있습니다

2024-10-17 07:57 UTC, hgh1472 commented on application/src/main/java/core/application/movies/models/entities/CommentEntity.java
>  	private Instant createdAt;
그 방법도 좋은 것 같아요!

2024-10-17 07:57 UTC, hgh1472 commented on application/src/main/java/core/application/movies/controller/MovieController.java
>  		// 잘못된 장르 검색 시, 아예 페이지 제공 X
맞네요...

2024-10-17 07:59 UTC, hgh1472 commented on application/src/main/java/core/application/users/service/UserServiceImpl.java
> +        if (userRepository.existsByUserId(userId)) {
어느정도는 기존 인터페이스에 맞춰서 구현하도록 했습니다!
민정님 말대로 저 로직에 맞춰서 JPA 형식으로 다듬었어요

2024-10-17 08:00 UTC, hgh1472 commented
@jbw9964 리뷰 형식으로 올리다보니 컴파일 에러가 꽤 있더라구요..
방금 다시 push해서 컴파일이랑 테스트는 돌아가도록 마쳤습니다! 막 변경하다보니 파일도 지저분하게 수정되어서 브랜치 다시파고 정리하면서 실제 Merge시킬 PR 올릴 계획입니다!

2024-10-17 08:05 UTC, TrixieL20 commented on application/src/main/java/core/application/users/service/UserServiceImpl.java
> +        if (userRepository.existsByUserId(userId)) {
저 부분이 오해의 소지가 있을 것 같아서 jpa 형식으로 가다듬어진 것이 develop에 반영되면 jpa가 던지는 exception에 따라 try catch 처리를 고려해보겠습니다! 감사합니다

2024-10-17 08:25 UTC, TrixieL20 commented on application/src/main/java/core/application/users/models/entities/UserEntity.java
>      private UUID     userId;
가능한 것으로 알고 있습니다.

2024-10-17 08:25 UTC, TrixieL20 commented on application/src/main/java/core/application/users/models/entities/UserEntity.java
> +        this.role = (userRequestDTO.getRole() != null ? userRequestDTO.getRole() : this.getRole()); // role 업데이트
이 role 부분은 빠져야 할 것 같아요.
role을 수정하는 것은 사용자보다 관리자가 할 수 있는 부분인 것 같아서 뺐어요.

2024-10-17 08:27 UTC, TrixieL20 commented on application/src/main/java/core/application/users/models/entities/UserEntity.java
> +        this.role = (userRequestDTO.getRole() != null ? userRequestDTO.getRole() : this.getRole()); // role 업데이트
이 role 부분은 빠져야 할 것 같아요.
role을 수정하는 것은 사용자보다 관리자가 할 수 있는 부분인 것 같아서 뺐어요.

2024-10-17 08:44 UTC, jbw9964 commented on application/src/main/java/core/application/users/models/entities/UserEntity.java
>      private UUID     userId;
`@GeneratedValue` 해도 되더라구요.

아마 `strategy` 의 `default` 가 `AUTO` 로 되어있어 `GenerationType.UUID` 로 알아서 설정되는 것 같습니다.

`(@GeneratedValue(strategy = GenerationType.UUID))`

2024-10-17 08:46 UTC, jbw9964 commented on application/src/main/java/core/application/movies/repositories/comment/JpaCommentRepository.java
> +			"CASE WHEN l.commentLikeId IS NOT NULL THEN true ELSE false END, " +
아 `CASE WHEN l.commentLikeId IS NOT NULL THEN true ELSE false END, ` 부분 여쭤본 거였습니다!

2024-10-17 08:49 UTC, jbw9964 commented on application/src/main/java/core/application/users/service/UserServiceImpl.java
> +        if (userRepository.existsByUserId(userId)) {
`JpaUserRepository` 에서 확인하니 `existsByUserId` 메서드는 `DB 에 유저가 있는지 확인` 하는 것으로 파악했습니다.

그런데 `userRepository.deleteUser(userId)` 로 `DB` 에서 유저를 삭제하면 `existsByUserId` 호출 시 `false` 가 나올텐데,

아래 로직을 보니 `true` 일 때 올바른 응답 메시지를 전달해서 여쭤본 거였습니다.

2024-10-18 01:34 UTC, TrixieL20 commented on application/src/main/java/core/application/users/service/UserServiceImpl.java
> +        if (userRepository.existsByUserId(userId)) {
준상님 코멘트 보고 확인해보니 `JpaUserRepository`에는 `existsByUserId`는 없고 'existsByUserEmail'은 있고 'UserRepository'에 `existsByUserId`가 있네요.
이렇게되면 문제가 발생하지 않나요? JpaUserRepository에도 existsByUserId가 있어야 하는 것 같은데...

2024-10-18 01:36 UTC, TrixieL20 commented on application/src/main/java/core/application/users/service/UserServiceImpl.java
> +        if (userRepository.existsByUserId(userId)) {
@jbw9964 아마 이부분이 저랑 소은님 건하님이 작성하게 되어서 서로 문제가 발생한 부분이 아닌가 싶네요. 소은님이 existsUserEmail 부분을 repository에 만들어두셨고 저는 그 부분을 활용하지 않고 service의 deleteUser 로직을 구현했고 건하님이 jpa로 마이그레이션하게 되면서 이렇게 된 것 같네요.

2024-10-19 04:28 UTC, jbw9964 commented
리뷰용 `PR` 이므로 `issue close`

2024-10-19 04:28 UTC, closed without merging