[Refactor] `movie` JPA 마이그레이
prgrms-be-devcourse/NBE1_2_Team10 pull request #142
Opened 2024-10-19 14:26 UTC by hgh1472

## 📌 과제 설명 

`movie` 도메인 리포지토리에 JPA를 추가하였습니다.

## 👩‍💻 요구 사항과 구현 내용 

주요한 코드 수정 내용은 다음과 같습니다!

- 기존 Entity에 JPA 관련 어노테이션 추가
    - 한줄평 좋아요/싫어요 6e8c9334ed8ed27117c8249cbc297d3bcd6a5d75
    - 영화 86d1e447bdf7a46438a9a06b4e4d738ed91b1419
    - 한줄평 1b37b87de85013b1a634551bdf47256ea0a22a08
- Entity 별 JPA 인터페이스 추가
    - 한줄평 좋아요/싫어요 e8ea018bf0ec57c292e3e36ee08e96b5310fa0c9
    - 한줄평 f68429645bb4f2905f34ba8c19861fcc59722ada
    - 영화 c456d72eddd3b4a57520d19e15b28e8a57d5cae9
- Entity 별 JPA 리포지토리 구현
    - 한줄평 좋아요/싫어요 3b9a441ce5b24aa5e92f3d2e3722d18e5422a3ac
    - 한줄평 275c282d6aa3d062fd81069be35d35fc3fc3a669
    - 영화 4b15fea24fa3094a857598d3156a483280a42dbe
- 서비스 코드 수정
    - 7ade541a4438ffd4bbb711e538293a69930318c3
- 컨트롤러 코드 수정
    - 7ade541a4438ffd4bbb711e538293a69930318c3
- 테스트 코드 수정
    - JPA, Mybatis에 따라 테스트하도록 수정 b7b9ef071d0239020ac0bcc8c1c6eb71491a81d1
    - 영화 평점 개수 0일 때, 테스트 코드 추가 d132e7250c338f855b1d5de3b4b00f655b9cd582
- 순환참조 오류 수정
    - JPA 리포지토리 구현체 클래스명 변경 59826dcd4398a36c25d98bbab435d758a4d3e723
- JPA 인터페이스 메서드명 변경
    - bc5425eddb9cb188853cac4d09aa348917d475bb
    - a84a1630e7183d674dc6caca39fea349e55945b0

## ✅ 피드백 반영사항 

- 평균 평점을 구하기 위해 `sumOfRating/commentCount` 연산을 하는데 소수점 5번째 자리에서 반올림하여 비교하는 것 같습니다.
- 이 때 `commentCount`가 0인 경우, mysql에서는 0인 컬럼이 제일 앞에 나오게 됩니다. 테스트 코드 작성 후 테스트 해보니 JPA는 `sumOfRating / commentCount` 에서 `commentCount`가 0이면 제일 하위로 주는 것 같습니다.

## ✅ PR 포인트 & 궁금한 점 <!-- 리뷰어 분들이 집중적으로 보셨으면 하는 내용을 적어주세요

2024-10-20 10:04 UTC, jbw9964 requested changes
`MyBatis` 프로필로만 테스트 해봤는데 계속 에러가 발생하네요.

거기다 `Service`, `Controller` 계층까지 수정되어 있어 너무 많은 변경점을 한 `PR` 에 넣은 것 같습니다.

기능별 `PR` 나눠서 보내주시면 검증하기 더 편할 것 같아요.

2024-10-20 10:04 UTC, jbw9964 commented on application/src/test/java/core/application/movies/repository/CommentRepositoryTest.java
> +		if (commentRepository.getClass() == MybatisCommentRepository.class) {
`instance of`

2024-10-20 11:14 UTC, hgh1472 commented on application/src/main/java/core/application/movies/controller/MovieController.java
> +	public ApiResponse<Page<MovieSearchRespDTO>> search(@RequestParam(defaultValue = "") String query,
Service 에서 직접 `PageImpl` 객체를 생성하고 전체 개수와 검색 결과를 넣어주는 방식으로 진행했습니다.

2024-10-20 11:16 UTC, hgh1472 commented on application/src/main/java/core/application/movies/models/entities/CommentDislike.java
> +public class CommentDislike {
이전에 마이바티스를 사용할 때 한줄평 좋아요/싫어요는 중간에 추가되기도 하였고, 좋아요/싫어요에 대한 로직도 간단하기 때문에 만들지 않고 진행했습니다.
JPA에서는 Entity가 필요하기 때문에 새로 생성하였습니다

2024-10-20 11:19 UTC, hgh1472 commented on application/src/main/java/core/application/movies/repositories/comment/jpa/JpaCommentDislikeRepository.java
> +    nativeQuery = true)
JPA에서 `@Query`를 사용해 직접 insert 하는 경우, `@Modifying`과 `nativeQuery=true`로 지정해야 하는 것으로 알고있습니다

2024-10-20 11:20 UTC, hgh1472 commented on application/src/main/resources/mappers/movies/CacheMovieMapper.xml
> +        where genre like %#{genre}%
`%`가 와일드카드 역할을 해서 `액션`장르를 검색했을 때, `액션, 범죄, 스릴러` 같이 장르가 저장되어있는 경우에도 조회할 수 있도록 하였습니다.

2024-10-20 11:21 UTC, hgh1472 commented on application/src/main/resources/mappers/movies/CommentMapper.xml
> +        count (*) from comment_table
select count(*)로 수정하겠습니다

2024-10-20 11:21 UTC, hgh1472 commented on application/src/main/java/core/application/movies/service/CommentService.java
> +		if (commentRepository.getClass() == MybatisCommentRepository.class) {
해당 부분도 `instanceof`로 수정하겠습니다.

2024-10-20 11:27 UTC, hgh1472 commented on application/src/main/java/core/application/movies/controller/CommentController.java
>  			userId = null;
Mybatis에서 위의 `CommentMapper`에서 `count` 쿼리가 잘못되어있어서 발생한 것 같습니다. 해당 부분 수정 시 에러 발생하지 않고 나오는 것 같아요.

2024-10-20 11:29 UTC, hgh1472 commented on application/src/main/java/core/application/movies/repositories/comment/jpa/JpaCommentRepository.java
> +            "CASE WHEN l.commentLikeId IS NOT NULL THEN true ELSE false END, " +
`WHEN l.commentLikeId IS NOT NULL` 이라는 문장을 `if`문이라고 생각하면 됩니다.
해당 문장이 true일 경우, `THEN true`에 따라 true를 반환하고, 해당하지 않는 경우 false를 반환합니다.
즉, `CASE`는 조건에 따라 값을 지정할 때 사용한다고 생각하시면 됩니다.

2024-10-20 11:32 UTC, hgh1472 commented on application/src/main/java/core/application/movies/repositories/comment/jpa/CommentRepositoryJPAImpl.java
> +    public List<CommentRespDTO> findByMovieId(String movieId, UUID userId, int page) {
JPA의 경우 페이징 처리 시 바로 `Page<CommentRespDTO>`로 건네줄 수 있기 때문에 `findByMovieIdOrderBy` 메서드를 이용하였습니다.
결국 인터페이스에 구현체에 따라 사용하는 메서드가 나뉘는 상황인데, 기존 Mybatis와 JPA 둘 다 사용할 수 있게 하는게 우선이다보니 JPA 전용 메서드, Mybatis 전용 메서드로 나뉘게 되었습니다.

2024-10-20 11:32 UTC, hgh1472 commented on application/src/main/java/core/application/movies/repositories/comment/CommentRepository.java
> +	Page<CommentRespDTO> findByMovieIdOrderBy(String movieId,  UUID userId, Pageable pageable);
위에 언급한 내용과 같게 JPA는 직접 Pageable을 통해 정렬 조건을 넣고 페이징 처리가 가능해서 JPA 구현체가 사용하는 메서드입니다

2024-10-20 11:33 UTC, hgh1472 commented on application/src/main/java/core/application/movies/repositories/movie/jpa/CachedMovieRepositoryJPAImpl.java
> +    public int countGenreMovie(String genre) {
위 내용과 같아요. 이후에 주석으로 작성해놓겠습니다.

2024-10-21 00:50 UTC, jbw9964 commented on application/src/main/java/core/application/movies/repositories/comment/jpa/CommentRepositoryJPAImpl.java
> +    public List<CommentRespDTO> findByMovieId(String movieId, UUID userId, int page) {
그럼 결국 `CASE WHEN` 부분은 올바른 `CommentRespDTO` 를 생성하기 위한 것이 맞나요?
생성자에 `entity` 속성에 따라 `false`, `true` 넣어주려고?

2024-10-21 00:52 UTC, jbw9964 commented on application/src/main/java/core/application/movies/repositories/comment/jpa/JpaCommentRepository.java
> +            "CASE WHEN l.commentLikeId IS NOT NULL THEN true ELSE false END, " +
그럼 결국 `CASE WHEN` 부분은 올바른 `CommentRespDTO` 를 생성하기 위한 것이 맞나요?
생성자에 `entity` 속성에 따라 `false`, `true` 넣어주는게 맞나요?

2024-10-21 01:23 UTC, jbw9964 commented on application/src/main/java/core/application/movies/repositories/comment/jpa/CommentRepositoryJPAImpl.java
> +    public List<CommentRespDTO> findByMovieId(String movieId, UUID userId, int page) {
그렇다면 `CommentRepository` 인터페이스에서 `JPA`, `MyBatis` 용 메서드를 구분하기 보다
담당하는 인터페이스의 반환 타입을 모두 `Page` 로 바꾸고 `MyBatis` 구현체에서 이를 `handle` 하는게 더 좋을 것 같아요.

```java
// CommentRepository.java (interface)

	/**
	 * 특정 영화에 달린 한줄평 댓글을 최신순으로 검색
	 *
	 * @param movieId 검색할 영화 ID
	 * @return {@link List}{@code <}{@link CommentEntity}{@code >}
	 */
// 원래는 List<CommentRespDTO> return
	Page<CommentRespDTO> findByMovieIdOnDateDescend(String movieId, UUID userId, int offset);
```

```java
// MybatisCommentRepository.java (구현체)

// List<CommentRespDTO> 에서 Page 로 변경 + 구현체 handle
	@Override
	public Page<CommentRespDTO> findByMovieIdOnDateDescend(String movieId, UUID userId, int offset) {
               Pageable pageable = PageRequest.of(page, 10);
               long total = commentRepository.countByMovieId(movieId);
               var result = commentMapper.findByMovieIdOnDateDescend(movieId, userId, offset);

	       return new PageImpl<>(result , pageable, total);
	}
```

이런 식으로

2024-10-21 01:24 UTC, jbw9964 commented on application/src/main/java/core/application/movies/repositories/comment/CommentRepository.java
> +	Page<CommentRespDTO> findByMovieIdOrderBy(String movieId,  UUID userId, Pageable pageable);
https://github.com/prgrms-be-devcourse/NBE1_2_Team10/pull/142#discussion_r1807999304

2024-10-21 01:24 UTC, jbw9964 commented on application/src/main/java/core/application/movies/repositories/movie/jpa/CachedMovieRepositoryJPAImpl.java
> +    public int countGenreMovie(String genre) {
https://github.com/prgrms-be-devcourse/NBE1_2_Team10/pull/142#discussion_r1807999304

2024-10-21 01:39 UTC, jbw9964 commented on application/src/main/java/core/application/movies/controller/CommentController.java
>  			userId = null;
그러네요 제가 착각한 부분이 있던것 같습니다.

2024-10-21 02:21 UTC, hgh1472 commented on application/src/main/java/core/application/movies/repositories/comment/jpa/CommentRepositoryJPAImpl.java
> +    public List<CommentRespDTO> findByMovieId(String movieId, UUID userId, int page) {
사실 두 방법 중에 고민하긴했는데, 한번 바꿔서 구현해봐야겠어요!

2024-10-21 06:28 UTC, jbw9964 commented
해당 `PR` 은 #144, #145 로 분리되었습니다.

2024-10-21 06:28 UTC, closed without merging